inherit_gem:
  rubocop-rootstrap:
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - db/schema.rb
    - config/initializers/pagy.rb
    - bin/bundle
    - bin/yarn

Layout/ClassStructure:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Exclude:
    - app/views/api/**/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Exclude:
    - db/migrate/20161011151353_devise_create_users.rb

Metrics/LineLength:
  Exclude:
    - db/migrate/20161011184702_devise_create_admin_users.rb
    - db/migrate/20161011151353_devise_create_users.rb
    - db/migrate/20161027190856_create_delayed_jobs.rb
    - db/migrate/20181102142200_create_active_storage_tables.active_storage.rb

Rails/Delegate:
  Exclude:
    - app/controllers/api/concerns/act_as_api_request.rb

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/SaveBang:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/ReturnNil:
  Enabled: true
